Repository ORNL-CEES/DataTransferKit, pull requests merged in 2018-12, with the labels that each got.

#503 Initialize MPI in all tests to resolve issue with CUDA hooks on OLCF machines
  packages/Interface/src/DTK_Fortran_wrap.cpp
  packages/Interface/src/dtk.i
  packages/Interface/test/tstFortran_API.f90
  packages/Interface/test/tstInit.cpp
Labels: Low Priority, bug, need review

#506 Fix for AddressSanitizer reports
  scripts/docker_clang60_env.sh
Labels: need review

#507 Do not let Jenkins build fail if performance benchmark regression fails
  docker/jenkins/build.sh
Labels: Performance, need review

#504 Small optimization for the GPU
  packages/Search/src/details/DTK_DetailsNode.hpp
  packages/Search/src/details/DTK_DetailsTreeConstruction_def.hpp
Labels: need review

#505 Add support for checking type of primitives for creating a bounding volume hierarchy
  packages/Search/src/DTK_LinearBVH_decl.hpp
  packages/Search/src/DTK_LinearBVH_def.hpp
  packages/Search/src/details/DTK_DetailsConcepts.hpp
Labels: Enhancement, need review

#508 Build bounding volume hierarchy directly from a point cloud
  packages/Search/examples/bvh_driver/bvh_driver.cpp
  packages/Search/src/DTK_LinearBVH_decl.hpp
  packages/Search/src/details/DTK_DetailsAlgorithms.hpp
  packages/Search/src/details/DTK_DetailsBatchedQueries.hpp
  packages/Search/src/details/DTK_DetailsTags.hpp
  packages/Search/src/details/DTK_DetailsTreeConstruction_decl.hpp
  packages/Search/src/details/DTK_DetailsTreeConstruction_def.hpp
Labels: Enhancement, New Feature, need review

#509 Cleanup distributed search tree
  packages/Search/src/DTK_DistributedSearchTree_decl.hpp
  packages/Search/src/DTK_DistributedSearchTree_def.hpp
  packages/Search/src/DTK_LinearBVH_decl.hpp
  packages/Search/src/details/DTK_DetailsBoundingVolumeHierarchyImpl.hpp
  packages/Search/src/details/DTK_DetailsDistributedSearchTreeImpl.hpp
Labels: Enhancement, need review

#511 Fixup for static assertion that doesnt hold anymore
  packages/Search/src/DTK_LinearBVH_def.hpp
Labels: bug, need review
