Repository ORNL-CEES/DataTransferKit, pull requests merged in 2018-10, with the labels that each got.

#470 Add boost rtree to benchmark
  packages/Search/examples/bvh_driver/bvh_driver.cpp
  packages/Search/src/DTK_LinearBVH_decl.hpp
  packages/Search/test/DTK_BoostRTreeHelpers.hpp
Labels: need review

#472 Fix a bug using CUDA 9
  packages/Discretization/src/DTK_PointSearch_def.hpp
Labels: Release

#401 Add support for CUDA 9.0 in jenkins
  docker/jenkins/build.sh
Labels: need review

#478 Get rid of global INCLUDE_DIRECTORIES
  packages/Utils/src/CMakeLists.txt
Labels: need review

#471 Performance
  docker/jenkins/build.sh
  docker/jenkins/docker-compose.yml
  scripts/compare.py
  scripts/performance_plot.py
  scripts/ref_gcc54_cuda8.json
Labels: need review

#479 Fix Jenkins scripts for flat package structure
  docker/jenkins/build.sh
  scripts/ref_gcc54_cuda8.json
Labels: need review

#473 Update CUDA package version for 9.2 in script to extend docker images
  docker/nvidia/setup_nvidia_docker_compose.py
Labels: need review

#475 Adding size arguments to field evaluation in C API
  packages/Interface/src/DTK_C_API.cpp
  packages/Interface/src/DTK_C_API.h
  packages/Interface/test/tstC_API.c
  packages/Interface/test/tstFortran_API.f90
Labels: bug, need review

#474 C API Documentation
  packages/Interface/src/DTK_C_API.h
  packages/Interface/src/DTK_DOFMap.hpp
  packages/MapFactory/src/DTK_C_API_Map.cpp
Labels: need review

#463 Fixes for release 3.0
  docs/source/install.rst
  docs/source/requirements.readthedocs.txt
  packages/Discretization/src/DTK_PointSearch_def.hpp
  packages/Interface/src/DTK_C_API.cpp
  packages/Interface/src/DTK_C_API.h
  packages/Interface/src/DTK_Fortran_API.F90
  packages/Interface/src/DTK_Fortran_wrap.cpp
  packages/Interface/src/dtk.i
  packages/Interface/test/tstC_API.c
  packages/Interface/test/tstFortran_API.f90
  packages/MapFactory/cmake/Dependencies.cmake
  packages/MapFactory/src/DTK_C_API_Map.cpp
  packages/MapFactory/src/DTK_C_API_Map.hpp
  packages/MapFactory/test/tstMapInterface.cpp
  packages/Meshfree/src/DTK_MovingLeastSquaresOperator_decl.hpp
  packages/Meshfree/src/DTK_MovingLeastSquaresOperator_def.hpp
  packages/Utils/src/DTK_Version.hpp
  packages/Utils/test/tstMiscellaneous.cpp
  scripts/check_no_trailing_whitespaces_or_tabs.sh
Labels: need review

#481 Interface: fix gitCommitHash in C API and Fortran
  packages/Interface/src/DTK_C_API.cpp
  packages/Interface/src/DTK_Fortran_API.F90
  packages/Interface/src/DTK_Fortran_wrap.cpp
  packages/Interface/src/dtk.i
  packages/Interface/test/tstC_API.c
Labels: need review

#482 Make signed great again
  docs/source/install.rst
  packages/Interface/test/DTK_TestApplicationHelpers.hpp
  packages/Utils/src/DTK_Types.h
  scripts/alcf_mira_cmake
  scripts/cades_shpc_condo_cmake
  scripts/docker_cmake
  scripts/kokkos_cuda_openmp_cmake
  scripts/olcf_summitdev_cmake
Labels: need review

#483 Cherry-pick signed commits to dtk-3.0
  docs/source/install.rst
  packages/Interface/test/DTK_TestApplicationHelpers.hpp
  packages/Interface/test/tstFortran_API.f90
  packages/Utils/src/DTK_Types.h
  scripts/alcf_mira_cmake
  scripts/cades_shpc_condo_cmake
  scripts/docker_cmake
  scripts/kokkos_cuda_openmp_cmake
  scripts/olcf_summitdev_cmake
Labels: need review

#484 Switching master to use GO "long long" instead of "int64_t"
  packages/Interface/test/tstFortran_API.f90
  packages/Utils/src/DTK_Types.h
Labels: need review

#485 Search: fix deplibs dependency for dtk_search
  packages/Search/src/CMakeLists.txt
Labels: need review

#486 Include necessary <array> headers
  packages/Discretization/src/DTK_Interpolation_decl.hpp
  packages/Discretization/src/DTK_PointSearch_decl.hpp
  packages/Discretization/src/DTK_Topology.hpp
  packages/Discretization/test/tstMeshGenerator.cpp
  packages/Discretization/test/tstPointInCell.cpp
  packages/Search/test/tstDetailsTreeConstruction.cpp
Labels: need review

#488 Include necessary <array> headers
  packages/Discretization/src/DTK_Interpolation_decl.hpp
  packages/Discretization/src/DTK_PointSearch_decl.hpp
  packages/Discretization/src/DTK_Topology.hpp
  packages/Discretization/test/tstMeshGenerator.cpp
  packages/Discretization/test/tstPointInCell.cpp
  packages/Search/test/tstDetailsTreeConstruction.cpp
Labels: need review

#489 Move morton3D and sortObjects out of TreeConstruction to DetailsUtils
  packages/Search/src/DTK_LinearBVH_decl.hpp
  packages/Search/src/details/DTK_DetailsBatchedQueries.hpp
  packages/Search/src/details/DTK_DetailsMortonCode.hpp
  packages/Search/src/details/DTK_DetailsSortUtils.hpp
  packages/Search/src/details/DTK_DetailsTreeConstruction_decl.hpp
  packages/Search/src/details/DTK_DetailsTreeConstruction_def.hpp
  packages/Search/test/tstDetailsTreeConstruction.cpp
Labels: need review

#493 Fix config generation
  CMakeLists.txt
  packages/Meshfree/src/CMakeLists.txt
  packages/Utils/src/CMakeLists.txt
Labels: bug, need review
