Repository ORNL-CEES/DataTransferKit, pull requests merged in 2018-09, with the labels that each got.

#432 Benchmark bvh construction as well as knn and radius searches
  docker/Dockerfile_stack
  docker/README.md
  packages/Search/examples/bvh_driver/CMakeLists.txt
  packages/Search/examples/bvh_driver/bvh_driver.cpp
Labels: need review

#435 Disable test that require mesh files if DTKData is missing
  packages/Meshfree/test/CMakeLists.txt
Labels: need review

#436 Do not include docker dir in tarball export of DTK
  .cproject
  .gitattributes
  .project
Labels: need review

#438 Bump DTK version to 3.1
  Version.cmake
Labels: need review

#441 Add description for MapFactory and Benchmark packages
  docs/source/overview.rst
Labels: need review

#442 Update Authors
  docs/source/conf.py
  docs/source/overview.rst
Labels: need review

#440 Update Version.cmake to reflect that it is a release
  Version.cmake
  docs/source/conf.py
Labels: need review

#443 Cherry picking two commits from master
  docs/source/conf.py
  docs/source/overview.rst
Labels: need review

#445 Improve installation documentation when using a tarball
  docs/source/install.rst
Labels: need review

#449 Do not require Boost.MPI and Boost.Serialization in release 3.0
  cmake/TPLs/FindTPLBoostOrg.cmake
Labels: need review

#450 Fortran fixes
  packages/Interface/CMakeLists.txt
  packages/Interface/test/CMakeLists.txt
  packages/Interface/test/tstFortran_API.f90
Labels: Release, need review

#452 Fix link to RTD in README
  README.md
Labels: need review

#453 Cherry-pick for fortran
  packages/Interface/CMakeLists.txt
  packages/Interface/test/CMakeLists.txt
  packages/Interface/test/tstFortran_API.f90
Labels: need review

#458 Remove C++ API from documentation published on ReadTheDocs
  docs/source/api.rst
  packages/Interface/src/DTK_C_API.h
Labels: need review

#456 Adding options string to map creation interface
  packages/Interface/src/DTK_C_API.h
  packages/MapFactory/cmake/Dependencies.cmake
  packages/MapFactory/src/DTK_C_API_Map.cpp
  packages/MapFactory/src/DTK_C_API_Map.hpp
  packages/MapFactory/test/tstMapInterface.cpp
Labels: need review

#460 Remove c++ api on read the docs
  docs/source/api.rst
  packages/Interface/src/DTK_C_API.h
Labels: need review

#462 Parse option string to create the appropriate point cloud map
  docs/source/install.rst
  packages/MapFactory/src/DTK_C_API_Map.hpp
  packages/MapFactory/test/tstMapInterface.cpp
  packages/Meshfree/src/DTK_MovingLeastSquaresOperator_decl.hpp
  packages/Meshfree/src/DTK_MovingLeastSquaresOperator_def.hpp
Labels: High Priority, Release, need review

#464 Use camel case in c api for consistency
  packages/Interface/src/DTK_C_API.cpp
  packages/Interface/src/DTK_C_API.h
  packages/Interface/src/DTK_Fortran_API.F90
  packages/Interface/src/DTK_Fortran_wrap.cpp
  packages/Interface/src/dtk.i
  packages/Interface/test/tstC_API.c
  packages/MapFactory/src/DTK_C_API_Map.cpp
  packages/Utils/src/DTK_Version.hpp
  packages/Utils/test/tstMiscellaneous.cpp
  scripts/check_no_trailing_whitespaces_or_tabs.sh
Labels: High Priority, Release, need review
